# USA Gymnast with best chances to medal in fx are:

- Simone Biles

KNeighborsClassifier keeps returning eveylynn lowe, who should be there

In [136]:
import pandas as pd
import numpy as np
from scipy import stats
from mlxtend.preprocessing import minmax_scaling
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.datasets import make_circles, make_classification, make_moons
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [137]:
# df = pd.read_csv('../../Combine_Data/women/fx_encoded.csv')
olymp = pd.read_csv('../../Data/cleandata22-23/encoded_w_olympics_fx.csv')
fxnames = pd.read_csv('../../Data/cleandata22-23/encoded_w_olympics_fxnames.csv')
fxolymp = pd.read_csv('../../Data/cleandata22-23/women22_23.csv')

df = pd.read_csv('../../Combine_Data/women/mult_fx_encoded.csv')


In [138]:
df=df.drop(columns=['tot_final',
       'tot_fin_d', 'tot_fin_ddiv', 'tot_fin_ddiv_rank'])

In [139]:
df.columns

Index(['Rank', 'D Score', 'E Score', 'Pen.', 'Total', 'year', 'medal', 'Name',
       'nation', 'round_0', 'round_final', 'round_qual'],
      dtype='object')

In [140]:
df

Rank  D Score  E Score  Pen.   Total  year  medal  Name  nation  round_0  \
0     1.0      6.2    8.266   0.0  14.466  2019      1    66      43    False   
1     2.0      5.6    7.833   0.0  13.433  2019      0    78      22    False   
2     3.0      5.2    8.100   0.0  13.300  2019      1   126      22    False   
3     4.0      5.4    7.933  -0.1  13.233  2019      0    94      31    False   
4     5.0      5.0    8.200   0.0  13.200  2019      0    93      13    False   
..    ...      ...      ...   ...     ...   ...    ...   ...     ...      ...   
284  68.0      4.9    6.366   0.0  11.266  2015      0    37      41    False   
285  70.0      4.4    6.833   0.0  11.233  2015      0   119      29    False   
286  72.0      3.6    7.500   0.0  11.100  2015      0     8      25    False   
287  74.0      5.1    6.333  -0.4  11.033  2015      0    45      41    False   
288  75.0      4.0    6.933   0.0  10.933  2015      0    10       5    False   

     round_final  round_qual  
0           True       False  
1           True       False  
2           True       False  
3           True       False  
4           True       False  
..           ...         ...  
284        False        True  
285        False        True  
286        False        True  
287        False        True  
288        False        True  

[289 rows x 12 columns]

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Rank         289 non-null    float64
 1   D Score      289 non-null    float64
 2   E Score      289 non-null    float64
 3   Pen.         289 non-null    float64
 4   Total        289 non-null    float64
 5   year         289 non-null    int64  
 6   medal        289 non-null    int64  
 7   Name         289 non-null    int64  
 8   nation       289 non-null    int64  
 9   round_0      289 non-null    bool   
 10  round_final  289 non-null    bool   
 11  round_qual   289 non-null    bool   
dtypes: bool(3), float64(5), int64(4)
memory usage: 21.3 KB


In [57]:
df.head()

Rank  D Score  E Score  Pen.   Total  year  medal  Name  nation  round_0  \
0   1.0      6.2    8.266   0.0  14.466  2019      1    66      43    False   
1   2.0      5.6    7.833   0.0  13.433  2019      0    78      22    False   
2   3.0      5.2    8.100   0.0  13.300  2019      1   126      22    False   
3   4.0      5.4    7.933  -0.1  13.233  2019      0    94      31    False   
4   5.0      5.0    8.200   0.0  13.200  2019      0    93      13    False   

   round_final  round_qual  
0         True       False  
1         True       False  
2         True       False  
3         True       False  
4         True       False

In [58]:
# june 6 2017 till 2020 olympics = 1529
# 2018 = 1164
# 2019 = 799
# 2020 = 433

# june 6 2013 till  2016 olympics = 1177
# 2014 = 812
# 2015 = 447
# 2016 = 90


# dats till 2024 olympics = 
# 2022 = 796
# 2023 = 431

In [59]:
y = df['medal']
X = df.drop(columns=['medal'])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [60]:
y = df['medal']
X = df.drop(columns=['medal'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize classifiers
classifiers = {
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "SVM": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Naive Bayes": GaussianNB(),
    "Neural Network": MLPClassifier(),
}

results = {}

# Iterate through each classifier
for name, clf in classifiers.items():
    # Create a pipeline with StandardScaler for classifiers that require it
    if name in ["SVM", "K-Nearest Neighbors", "Neural Network"]:
        clf = make_pipeline(StandardScaler(), clf)

    # Fit the model to the training data
    clf.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_test)

    # Evaluate the model's performance
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)

    results[name] = {
        "accuracy": accuracy,
        "classification_report": report,
        "confusion_matrix": conf_matrix,
    }

# Print the results
for name, result in results.items():
    print(f"Classifier: {name}")
    print(f"Accuracy: {result['accuracy']:.4f}")
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}\n")


/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m

Classifier: Random Forest
Accuracy: 0.9655
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        56
           1       0.50      0.50      0.50         2

    accuracy                           0.97        58
   macro avg       0.74      0.74      0.74        58
weighted avg       0.97      0.97      0.97        58

Confusion Matrix:
[[55  1]
 [ 1  1]]

Classifier: AdaBoost
Accuracy: 0.9483
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.96      0.97        56
           1       0.33      0.50      0.40         2

    accuracy                           0.95        58
   macro avg       0.66      0.73      0.69        58
weighted avg       0.96      0.95      0.95        58

Confusion Matrix:
[[54  2]
 [ 1  1]]

Classifier: SVM
Accuracy: 0.9655
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.0

/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


using days instead of year

Classifier: Random Forest
Accuracy: 0.9659

Classifier: AdaBoost
Accuracy: 0.9659

---


Classifier: Random Forest
Accuracy: 0.9659

Classifier: SVM
Accuracy: 0.9545

Classifier: K-Nearest Neighbors
Accuracy: 0.9659

Classifier: Neural Network
Accuracy: 0.9659

Classifier: AdaBoost
Accuracy: 0.9659

In [113]:

# Assuming you already have your DataFrame 'df' and the target variable is 'medal'
y = df['medal']
X = df.drop(columns=['medal'])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15,
                                                    random_state=42)

# Initialize the AdaBoost classifier
clf = AdaBoostClassifier(n_estimators=1000, learning_rate=.00047,
                         random_state=42)

# Fit the model to the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the results
print("AdaBoost Classifier")
print(f"Accuracy: {accuracy:.4f}")
print(f"Classification Report:\n{report}")
print(f"Confusion Matrix:\n{conf_matrix}")


AdaBoost Classifier
Accuracy: 0.9545
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        42
           1       0.50      0.50      0.50         2

    accuracy                           0.95        44
   macro avg       0.74      0.74      0.74        44
weighted avg       0.95      0.95      0.95        44

Confusion Matrix:
[[41  1]
 [ 1  1]]


In [101]:
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.gaussian_process import GaussianProcessClassifier
# from sklearn.gaussian_process.kernels import RBF
# from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# # Assuming 'medal' is the target variable
# X = df.drop('medal', axis=1)
# y = df['medal']

# # Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Initialize Gaussian Process Classifier with Radial Basis Function (RBF) kernel
# kernel = 1.0 * RBF(length_scale=1.0)
# gpc = GaussianProcessClassifier(kernel=kernel, random_state=42)

# # Fit the model to the training data
# gpc.fit(X_train, y_train)

# # Predict on the test set
# y_pred_gpc = gpc.predict(X_test)

# # Evaluate the model's performance
# accuracy_gpc = accuracy_score(y_test, y_pred_gpc)
# report_gpc = classification_report(y_test, y_pred_gpc)
# conf_matrix_gpc = confusion_matrix(y_test, y_pred_gpc)

# # Print the results
# print("Gaussian Process Classifier")
# print(f"Accuracy: {accuracy_gpc:.4f}")
# print(f"Classification Report:\n{report_gpc}")
# print(f"Confusion Matrix:\n{conf_matrix_gpc}")


Gaussian Process Classifier
Accuracy: 0.9828
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        56
           1       1.00      0.50      0.67         2

    accuracy                           0.98        58
   macro avg       0.99      0.75      0.83        58
weighted avg       0.98      0.98      0.98        58

Confusion Matrix:
[[56  0]
 [ 1  1]]


In [100]:
# from sklearn.gaussian_process import GaussianProcessClassifier
# from sklearn.gaussian_process.kernels import RBF, Matern
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score

# # Assuming 'medal' is the target variable
# X = df.drop('medal', axis=1)
# y = df['medal']

# # Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, 
#                                                     test_size=0.20, 
#                                                     random_state=42)

# # Adjusting the kernel and its parameters
# kernel = 1.0 * Matern(length_scale=1.0, nu=1.5)  # Example with Matern kernel
# gpc = GaussianProcessClassifier(kernel=kernel,n_restarts_optimizer=9,
#                                 optimizer='fmin_l_bfgs_b',
#                                 random_state=42)

# # Fit the model to the training data
# gpc.fit(X_train, y_train)

# # Predict on the test set
# y_pred_gpc = gpc.predict(X_test)

# # Evaluate the model's performance
# accuracy_gpc = accuracy_score(y_test, y_pred_gpc)
# report_gpc = classification_report(y_test, y_pred_gpc)
# conf_matrix_gpc = confusion_matrix(y_test, y_pred_gpc)

# # Print the results
# print("Gaussian Process Classifier")
# print(f"Accuracy: {accuracy_gpc:.4f}")
# print(f"Classification Report:\n{report_gpc}")
# print(f"Confusion Matrix:\n{conf_matrix_gpc}")

In [87]:
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestClassifier, StackingClassifier, AdaBoostClassifier
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.linear_model import LogisticRegression
# from catboost import CatBoostClassifier
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# # Assuming 'medal' is the target variable
# X = df.drop('medal', axis=1)
# y = df['medal']

# # Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Initialize individual classifiers
# rf = RandomForestClassifier()
# knn = KNeighborsClassifier()
# adaboost = AdaBoostClassifier(n_estimators=50, random_state=42)
# catboost_model = CatBoostClassifier(iterations=100, depth=6, learning_rate=0.1, loss_function='Logloss', random_state=42)

# # Initialize StackingClassifier with a Decision Tree as the meta-classifier
# stacking_clf = StackingClassifier(
#     estimators=[('rf', rf), ('knn', knn), ('adaboost', adaboost), ('catboost', catboost_model)],
#     final_estimator=DecisionTreeClassifier(),
#     stack_method='auto',
#     n_jobs=-1,  # Set the number of jobs to -1 for parallel processing
#     passthrough=True
# )

# # Fit the StackingClassifier to the training data
# stacking_clf.fit(X_train, y_train)

# # Predict on the test set
# y_pred_stacking = stacking_clf.predict(X_test)

# # Evaluate the model's performance
# accuracy_stacking = accuracy_score(y_test, y_pred_stacking)
# report_stacking = classification_report(y_test, y_pred_stacking)
# conf_matrix_stacking = confusion_matrix(y_test, y_pred_stacking)

# # Print the results
# print("Stacking Classifier")
# print(f"Accuracy: {accuracy_stacking:.4f}")
# print(f"Classification Report:\n{report_stacking}")
# print(f"Confusion Matrix:\n{conf_matrix_stacking}")


In [114]:
olymp = pd.read_csv('../../Data/cleandata22-23/encoded_w_olympics_fx.csv')


In [115]:
olymp=olymp.drop(columns=['round_aafinal', 'round_teamfinal'])

In [116]:
olymp['round_0']=False

In [117]:
olymp.columns

Index(['Rank', 'D Score', 'E Score', 'Pen.', 'Total', 'year', 'Name', 'nation',
       'round_final', 'round_qual', 'round_teamqual', 'round_0'],
      dtype='object')

In [118]:
# Define the desired column order
desired_order = ['Rank', 'D Score', 'E Score', 'Pen.', 'Total', 'year', 'Name', 'nation',
       'round_0', 'round_final', 'round_qual']

# Reorder the columns based on the desired order
olymp = olymp[desired_order]

In [119]:
# y_pred = clf.predict(olymp)
y_pred = clf.predict(olymp)


In [120]:
ypreds  = pd.Series(y_pred)

In [121]:
olymp['ypred']=ypreds

In [122]:
olymp['ypred'].value_counts()

ypred
0    2114
1       2
Name: count, dtype: int64

In [123]:
filtered_df = olymp[olymp['ypred'] == 1]

In [124]:
filtered_df['Name'].unique()

array([642])

In [125]:
# List of Name_encoded values to filter by
name_encoded_values = [642]

# Create an empty set to store unique names
unique_names = set()

# Iterate through the DataFrame and add unique names to the set
for index, row in fxnames.iterrows():
    if row['Name_encoded'] in name_encoded_values:
        unique_names.add(row['Name'])

# Convert the set of unique names back to a list
unique_names_list = list(unique_names)


In [126]:
unique_names_list

['simone biles']

In [127]:
fxolymp['Name'] = fxolymp['Name'].str.lower()

In [132]:
names_to_find = ['simone biles']

# Filter the DataFrame to get the desired names and their corresponding countries
result_df = fxolymp[fxolymp['Name'].isin(names_to_find)]


In [133]:
result_df=result_df[result_df['Apparatus']== 'FX']

In [134]:
usa = result_df[result_df['Country']=='USA']

In [135]:
usa['Name'].unique()

array(['simone biles'], dtype=object)

0:	learn: 0.6324265	total: 51.9ms	remaining: 5.13s
0:	learn: 0.6409071	total: 47.8ms	remaining: 4.73s
1:	learn: 0.6005675	total: 48.6ms	remaining: 2.38s
1:	learn: 0.5977212	total: 52.9ms	remaining: 2.59s
2:	learn: 0.5571538	total: 49.2ms	remaining: 1.59s
2:	learn: 0.5544301	total: 53.5ms	remaining: 1.73s
3:	learn: 0.5204463	total: 50.2ms	remaining: 1.2s
3:	learn: 0.5150054	total: 54.7ms	remaining: 1.31s
0:	learn: 0.6389777	total: 44.2ms	remaining: 4.38s
4:	learn: 0.4909032	total: 51.3ms	remaining: 974ms
4:	learn: 0.4826168	total: 56ms	remaining: 1.06s
1:	learn: 0.5992796	total: 45.3ms	remaining: 2.22s
5:	learn: 0.4624182	total: 52.2ms	remaining: 817ms
2:	learn: 0.5554145	total: 45.9ms	remaining: 1.49s
5:	learn: 0.4478984	total: 57.1ms	remaining: 894ms
6:	learn: 0.4420440	total: 53.3ms	remaining: 708ms
6:	learn: 0.4207385	total: 58ms	remaining: 770ms
3:	learn: 0.5210086	total: 47.3ms	remaining: 1.14s
7:	learn: 0.4203204	total: 54.3ms	remaining: 625ms
7:	learn: 0.3964785	total: 58.9ms	re

0:	learn: 0.6538503	total: 52.6ms	remaining: 5.21s
1:	learn: 0.5967448	total: 53.2ms	remaining: 2.61s
2:	learn: 0.5505670	total: 53.7ms	remaining: 1.74s
3:	learn: 0.5209018	total: 54.2ms	remaining: 1.3s
4:	learn: 0.4903723	total: 54.7ms	remaining: 1.04s
0:	learn: 0.6607829	total: 45ms	remaining: 4.45s
5:	learn: 0.4560882	total: 55.3ms	remaining: 866ms
1:	learn: 0.6131315	total: 45.4ms	remaining: 2.23s
6:	learn: 0.4247306	total: 55.7ms	remaining: 740ms
2:	learn: 0.5647826	total: 45.7ms	remaining: 1.48s
7:	learn: 0.4007623	total: 56ms	remaining: 644ms
3:	learn: 0.5266843	total: 45.9ms	remaining: 1.1s
8:	learn: 0.3758483	total: 56.5ms	remaining: 571ms
4:	learn: 0.4997334	total: 46.4ms	remaining: 881ms
9:	learn: 0.3564658	total: 56.9ms	remaining: 512ms
5:	learn: 0.4722184	total: 46.8ms	remaining: 733ms
10:	learn: 0.3382504	total: 57.5ms	remaining: 465ms
6:	learn: 0.4473912	total: 47.4ms	remaining: 630ms
0:	learn: 0.6585515	total: 49.7ms	remaining: 4.92s
1:	learn: 0.6147761	total: 50.4ms	re

0:	learn: 0.6380288	total: 56.5ms	remaining: 5.59s
1:	learn: 0.5899585	total: 57.5ms	remaining: 2.82s
2:	learn: 0.5464777	total: 58ms	remaining: 1.87s
3:	learn: 0.5158998	total: 58.9ms	remaining: 1.41s
4:	learn: 0.4842561	total: 59.8ms	remaining: 1.14s
5:	learn: 0.4535592	total: 60.5ms	remaining: 948ms
6:	learn: 0.4273978	total: 61.3ms	remaining: 815ms
7:	learn: 0.4038832	total: 62ms	remaining: 713ms
8:	learn: 0.3861543	total: 62.8ms	remaining: 635ms
9:	learn: 0.3691576	total: 63.4ms	remaining: 570ms
10:	learn: 0.3524267	total: 64.2ms	remaining: 520ms
11:	learn: 0.3361380	total: 64.9ms	remaining: 476ms
12:	learn: 0.3212480	total: 65.5ms	remaining: 439ms
13:	learn: 0.3066629	total: 66.2ms	remaining: 406ms
14:	learn: 0.2947568	total: 66.8ms	remaining: 379ms
15:	learn: 0.2833641	total: 67.5ms	remaining: 354ms
16:	learn: 0.2707940	total: 68.2ms	remaining: 333ms
17:	learn: 0.2640842	total: 68.9ms	remaining: 314ms
18:	learn: 0.2564310	total: 69.6ms	remaining: 297ms
19:	learn: 0.2478074	total

0:	learn: 0.6600288	total: 56.2ms	remaining: 5.57s
1:	learn: 0.6097794	total: 57.1ms	remaining: 2.8s
2:	learn: 0.5616340	total: 57.8ms	remaining: 1.87s
3:	learn: 0.5306022	total: 58.3ms	remaining: 1.4s
4:	learn: 0.4978792	total: 59.2ms	remaining: 1.12s
5:	learn: 0.4637856	total: 59.8ms	remaining: 936ms
6:	learn: 0.4318765	total: 60.3ms	remaining: 802ms
7:	learn: 0.4099187	total: 60.8ms	remaining: 699ms
8:	learn: 0.3881105	total: 61.3ms	remaining: 620ms
9:	learn: 0.3713954	total: 61.8ms	remaining: 556ms
10:	learn: 0.3515160	total: 62.3ms	remaining: 504ms
11:	learn: 0.3333734	total: 62.7ms	remaining: 460ms
12:	learn: 0.3182157	total: 63.2ms	remaining: 423ms
13:	learn: 0.3033625	total: 63.6ms	remaining: 391ms
14:	learn: 0.2900491	total: 63.7ms	remaining: 361ms
15:	learn: 0.2789813	total: 64.2ms	remaining: 337ms
16:	learn: 0.2690207	total: 64.6ms	remaining: 316ms
17:	learn: 0.2580803	total: 65.1ms	remaining: 296ms
18:	learn: 0.2467708	total: 65.6ms	remaining: 280ms
19:	learn: 0.2386122	tot