# USA
- stephen nedoroscik
- khoi young

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from mlxtend.preprocessing import minmax_scaling
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.datasets import make_circles, make_classification, make_moons
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
df = pd.read_csv('../../Combine_Data/men/ph_encoded.csv')
olymp = pd.read_csv('../../Data/cleandata22-23/encoded_m_olympics_ph.csv')
phnames = pd.read_csv('../../Data/cleandata22-23/encoded_m_olympics_phnames.csv')
pholymp = pd.read_csv('../../Data/cleandata22-23/men22_23.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 561 entries, 0 to 560
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Rank         561 non-null    int64  
 1   D            561 non-null    float64
 2   E            561 non-null    float64
 3   ND           561 non-null    float64
 4   Total        561 non-null    float64
 5   year         561 non-null    int64  
 6   medal        561 non-null    int64  
 7   Name         561 non-null    int64  
 8   Nation       561 non-null    int64  
 9   round_final  561 non-null    bool   
 10  round_qual   561 non-null    bool   
dtypes: bool(2), float64(4), int64(5)
memory usage: 40.7 KB


In [5]:
y = df['medal']
X = df.drop(columns=['medal'])

# Split the data into training and testing sets
# CHANGED RANDOM STATE TO HAVE A LARGER NUMBER OF VALUES IN TEST DF
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize classifiers
classifiers = {
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "SVM": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Naive Bayes": GaussianNB(),
    "Neural Network": MLPClassifier(),
}

results = {}

# Iterate through each classifier
for name, clf in classifiers.items():
    # Create a pipeline with StandardScaler for classifiers that require it
    if name in ["SVM", "K-Nearest Neighbors", "Neural Network"]:
        clf = make_pipeline(StandardScaler(), clf)

    # Fit the model to the training data
    clf.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_test)

    # Evaluate the model's performance
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)

    results[name] = {
        "accuracy": accuracy,
        "classification_report": report,
        "confusion_matrix": conf_matrix,
    }

# Print the results
for name, result in results.items():
    print(f"Classifier: {name}")
    print(f"Accuracy: {result['accuracy']:.4f}")
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}\n")


/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m

Classifier: Random Forest
Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       112
           1       1.00      1.00      1.00         1

    accuracy                           1.00       113
   macro avg       1.00      1.00      1.00       113
weighted avg       1.00      1.00      1.00       113

Confusion Matrix:
[[112   0]
 [  0   1]]

Classifier: AdaBoost
Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       112
           1       1.00      1.00      1.00         1

    accuracy                           1.00       113
   macro avg       1.00      1.00      1.00       113
weighted avg       1.00      1.00      1.00       113

Confusion Matrix:
[[112   0]
 [  0   1]]

Classifier: SVM
Accuracy: 0.9912
Classification Report:
              precision    recall  f1-score   support

           0       0.99 

/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-

Classifier: Random Forest, AdaBoost, and Decision Tree
Accuracy: 0.9904

In [10]:
X_train.head()

Rank    D      E   ND   Total  year  Name  Nation  round_final  \
463   186  5.1  4.700  0.0   9.800  2019   261      78        False   
0       1  6.5  8.766  0.0  15.266  2019   173      78         True   
11      4  6.1  8.133  0.0  14.233  2019   297      11        False   
287    10  6.5  8.100  0.0  14.600  2019   233      73        False   
22     15  5.1  6.633  0.0  11.733  2019   181      26        False   

     round_qual  
463        True  
0         False  
11         True  
287        True  
22         True

In [11]:
olymp.head()


Rank    D      E   ND   Total  year  Name  Nation  round_final  round_qual
0  33.0  4.2  6.666  0.0  10.866  2022   232      64        False        True
1  33.0  4.2  6.666  0.0  10.866  2022   232      64        False        True
2  44.0  4.4  7.800  0.0  12.200  2023   232      64        False        True
3  58.0  4.4  7.266  0.0  11.666  2023   232      64        False        True
4  21.0  5.1  6.166  0.0  11.266  2022   518      29        False       False

In [8]:
olymp.rename(columns={'D Score': 'D', 'E Score': 'E',
                     'Pen.': 'ND', 'nation': 'Nation'}, inplace=True)

In [9]:
olymp=olymp.drop(columns=['round_TeamFinal', 'round_AAfinal', 'round_TeamQual'])

In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

data = df.copy()  

y = data['medal']
X = data.drop(columns=['medal'])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=2)

# Initialize and train the RandomForestClassifier with a specific number of estimators
n_estimators = 5  # Adjust this value to control the number of results
rf_model = RandomForestClassifier(n_estimators=n_estimators, random_state=42)
rf_model.fit(X_train, y_train)

# Make predictions with the RandomForestClassifier
y_pred = rf_model.predict(X_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy of RandomForest Classifier: {accuracy:.4f}")


Accuracy of RandomForest Classifier: 1.0000


In [13]:
y_predz = rf_model.predict(olymp)

In [14]:
ypreds  = pd.Series(y_predz)
olymp['ypredz']=ypreds

In [15]:
olymp['ypredz'].value_counts()


ypredz
0    2537
1      21
Name: count, dtype: int64

In [16]:
filtered_df = olymp[olymp['ypredz'] == 1]

In [17]:
filtered_df['Name'].unique()

array([520, 566, 282, 123, 673, 229, 276, 163, 278, 395])

In [18]:
name_encoded_values =  [520, 566, 282, 123, 673, 229, 276, 163, 278, 395]

# Filter the DataFrame to get the corresponding "Name" values
result = phnames.loc[phnames['Name_encoded'].isin(name_encoded_values), 'Name']


In [20]:
result.unique()

array(['ngoc xuan thien dang', 'patrick hoopes', 'illia kovtun',
       'chih kai lee', 'stephen nedoroscik', 'fred richard',
       'ian skirkey', 'dehang yin', 'ignacio yockers', 'khoi young'],
      dtype=object)

In [21]:
pholymp["Name"]=pholymp["Name"].str.lower()

In [22]:
names_to_filter = ['ngoc xuan thien dang', 'patrick hoopes', 'illia kovtun',
       'chih kai lee', 'stephen nedoroscik', 'fred richard',
       'ian skirkey', 'dehang yin', 'ignacio yockers', 'khoi young']

# Filter the DataFrame to get rows with the specified "Name" values
result = pholymp[pholymp['Name'].isin(names_to_filter)]

In [23]:
result['Country'].value_counts()

Country
UKR    151
USA    114
TPE     21
CHN     17
VIE      6
Name: count, dtype: int64

In [24]:
usas=result[result['Country']=='USA']

In [25]:
usas['Name'].unique()

array(['patrick hoopes', 'stephen nedoroscik', 'fred richard',
       'ian skirkey', 'ignacio yockers', 'khoi young'], dtype=object)