# USA
- stephen nedoroscik


In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from mlxtend.preprocessing import minmax_scaling
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.datasets import make_circles, make_classification, make_moons
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
df = pd.read_csv('../../Combine_Data/men/ph_encoded.csv')
olymp = pd.read_csv('../../Data/cleandata22-23/encoded_m_olympics_ph.csv')
phnames = pd.read_csv('../../Data/cleandata22-23/encoded_m_olympics_phnames.csv')
pholymp = pd.read_csv('../../Data/cleandata22-23/men22_23.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Rank         535 non-null    int64  
 1   D            535 non-null    float64
 2   E            535 non-null    float64
 3   ND           535 non-null    float64
 4   Total        535 non-null    float64
 5   year         535 non-null    int64  
 6   medal        535 non-null    int64  
 7   Name         535 non-null    int64  
 8   Nation       535 non-null    int64  
 9   round_final  535 non-null    bool   
 10  round_qual   535 non-null    bool   
dtypes: bool(2), float64(4), int64(5)
memory usage: 38.8 KB


In [4]:
y = df['medal']
X = df.drop(columns=['medal'])

# Split the data into training and testing sets
# CHANGED RANDOM STATE TO HAVE A LARGER NUMBER OF VALUES IN TEST DF
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize classifiers
classifiers = {
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "SVM": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Naive Bayes": GaussianNB(),
    "Neural Network": MLPClassifier(),
}

results = {}

# Iterate through each classifier
for name, clf in classifiers.items():
    # Create a pipeline with StandardScaler for classifiers that require it
    if name in ["SVM", "K-Nearest Neighbors", "Neural Network"]:
        clf = make_pipeline(StandardScaler(), clf)

    # Fit the model to the training data
    clf.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_test)

    # Evaluate the model's performance
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)

    results[name] = {
        "accuracy": accuracy,
        "classification_report": report,
        "confusion_matrix": conf_matrix,
    }

# Print the results
for name, result in results.items():
    print(f"Classifier: {name}")
    print(f"Accuracy: {result['accuracy']:.4f}")
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}\n")


/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m

Classifier: Random Forest
Accuracy: 0.9813
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       105
           1       0.00      0.00      0.00         2

    accuracy                           0.98       107
   macro avg       0.49      0.50      0.50       107
weighted avg       0.96      0.98      0.97       107

Confusion Matrix:
[[105   0]
 [  2   0]]

Classifier: AdaBoost
Accuracy: 0.9813
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       105
           1       0.00      0.00      0.00         2

    accuracy                           0.98       107
   macro avg       0.49      0.50      0.50       107
weighted avg       0.96      0.98      0.97       107

Confusion Matrix:
[[105   0]
 [  2   0]]

Classifier: SVM
Accuracy: 0.9813
Classification Report:
              precision    recall  f1-score   support

           0       0.98 

/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-

Classifier: Random Forest, AdaBoost, and Decision Tree
Accuracy: 0.9904

In [5]:
X_train.head()

Rank    D      E   ND   Total  year  Name  Nation  round_final  \
284     7  6.3  8.366  0.0  14.666  2019    68      26        False   
347    70  5.0  7.800  0.0  12.800  2019   118       1        False   
440   162  4.8  6.100  0.0  10.900  2019    14      72        False   
421   144  4.9  6.600  0.0  11.500  2019   314      43        False   
149    83  3.6  7.900  0.0  11.500  2018   307      35        False   

     round_qual  
284        True  
347        True  
440        True  
421        True  
149        True

In [6]:
olymp.head()


Rank  D Score  E Score  Pen.   Total  year  Name  nation  round_AAfinal  \
0  33.0      4.2    6.666   0.0  10.866  2022   232      64          False   
1  33.0      4.2    6.666   0.0  10.866  2022   232      64          False   
2  44.0      4.4    7.800   0.0  12.200  2023   232      64          False   
3  58.0      4.4    7.266   0.0  11.666  2023   232      64          False   
4  21.0      5.1    6.166   0.0  11.266  2022   518      29           True   

   round_TeamFinal  round_TeamQual  round_final  round_qual  
0            False           False        False        True  
1            False           False        False        True  
2            False           False        False        True  
3            False           False        False        True  
4            False           False        False       False

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

data = df.copy()  

y = data['medal']
X = data.drop(columns=['medal'])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# Initialize the AdaBoost classifier
clf = AdaBoostClassifier()

# Fit the model to the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the results
print("AdaBoost Classifier")
print(f"Accuracy: {accuracy:.4f}")
print(f"Classification Report:\n{report}")
print(f"Confusion Matrix:\n{conf_matrix}")

AdaBoost Classifier
Accuracy: 0.9813
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       105
           1       0.00      0.00      0.00         2

    accuracy                           0.98       107
   macro avg       0.49      0.50      0.50       107
weighted avg       0.96      0.98      0.97       107

Confusion Matrix:
[[105   0]
 [  2   0]]


/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m

In [8]:
olymp = pd.read_csv('../../Data/cleandata22-23/encoded_m_olympics_ph.csv')


In [9]:
olymp.rename(columns={'D Score': 'D', 'E Score': 'E',
                     'Pen.': 'ND', 'nation': 'Nation'}, inplace=True)

In [10]:
olymp=olymp.drop(columns=['round_TeamFinal', 'round_AAfinal', 'round_TeamQual'])

In [16]:
y_predz = clf.predict(olymp)

In [17]:
ypreds  = pd.Series(y_predz)
olymp['ypredz']=ypreds

In [18]:
olymp['ypredz'].value_counts()


ypredz
0    2549
1       9
Name: count, dtype: int64

In [19]:
filtered_df = olymp[olymp['ypredz'] == 1]

In [20]:
filtered_df['Name'].unique()

array([511, 356, 673, 473, 474])

In [21]:
name_encoded_values = [511, 356, 673, 473, 474]

# Filter the DataFrame to get the corresponding "Name" values
result = phnames.loc[phnames['Name_encoded'].isin(name_encoded_values), 'Name']


In [23]:
result.unique()

array(['nariman kurbanov', 'joshua nathan', 'stephen nedoroscik',
       'max whitlock', 'max whitlock obe'], dtype=object)

In [24]:
pholymp["Name"]=pholymp["Name"].str.lower()

In [25]:
names_to_filter = ['nariman kurbanov', 'joshua nathan', 'stephen nedoroscik',
       'max whitlock', 'max whitlock obe']

# Filter the DataFrame to get rows with the specified "Name" values
result = pholymp[pholymp['Name'].isin(names_to_filter)]

In [26]:
result['Country'].value_counts()

Country
GBR    57
KAZ    31
USA    12
Name: count, dtype: int64

In [27]:
usas=result[result['Country']=='USA']

In [28]:
usas['Name'].unique()

array(['stephen nedoroscik'], dtype=object)