# USA unlikely to medal

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from mlxtend.preprocessing import minmax_scaling
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.datasets import make_circles, make_classification, make_moons
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
df = pd.read_csv('../../Combine_Data/men/sr_encoded.csv')
olymp = pd.read_csv('../../Data/cleandata22-23/encoded_m_olympics_sr.csv')
srnames = pd.read_csv('../../Data/cleandata22-23/encoded_m_olympics_srnames.csv')
srolymp = pd.read_csv('../../Data/cleandata22-23/men22_23.csv')

In [3]:
df['year'].fillna(2023, inplace=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495 entries, 0 to 494
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Rank         495 non-null    int64  
 1   D            495 non-null    float64
 2   E            495 non-null    float64
 3   ND           495 non-null    float64
 4   Total        495 non-null    float64
 5   year         495 non-null    float64
 6   medal        495 non-null    int64  
 7   Name         495 non-null    int64  
 8   Nation       495 non-null    int64  
 9   round_final  495 non-null    bool   
 10  round_qual   495 non-null    bool   
dtypes: bool(2), float64(5), int64(4)
memory usage: 35.9 KB


In [5]:
y = df['medal']
X = df.drop(columns=['medal'])

# Split the data into training and testing sets
# CHANGED RANDOM STATE TO HAVE A LARGER NUMBER OF VALUES IN TEST DF
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=110)

# Initialize classifiers
classifiers = {
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "SVM": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Naive Bayes": GaussianNB(),
    "Neural Network": MLPClassifier(),
}

results = {}

# Iterate through each classifier
for name, clf in classifiers.items():
    # Create a pipeline with StandardScaler for classifiers that require it
    if name in ["SVM", "K-Nearest Neighbors", "Neural Network"]:
        clf = make_pipeline(StandardScaler(), clf)

    # Fit the model to the training data
    clf.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_test)

    # Evaluate the model's performance
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)

    results[name] = {
        "accuracy": accuracy,
        "classification_report": report,
        "confusion_matrix": conf_matrix,
    }

# Print the results
for name, result in results.items():
    print(f"Classifier: {name}")
    print(f"Accuracy: {result['accuracy']:.4f}")
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}\n")


/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m

Classifier: Random Forest
Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       122
           1       1.00      1.00      1.00         2

    accuracy                           1.00       124
   macro avg       1.00      1.00      1.00       124
weighted avg       1.00      1.00      1.00       124

Confusion Matrix:
[[122   0]
 [  0   2]]

Classifier: AdaBoost
Accuracy: 0.9919
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       122
           1       0.67      1.00      0.80         2

    accuracy                           0.99       124
   macro avg       0.83      1.00      0.90       124
weighted avg       0.99      0.99      0.99       124

Confusion Matrix:
[[121   1]
 [  0   2]]

Classifier: SVM
Accuracy: 0.9839
Classification Report:
              precision    recall  f1-score   support

           0       0.98 

/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-

Classifier: AdaBoost
Accuracy: 0.9923

Classifier: Decision Tree
Accuracy: 0.9923

In [6]:
X_train.head()

Rank    D      E   ND   Total    year  Name  Nation  round_final  \
71     13  6.1  8.200  0.0  14.300  2018.0    86      60        False   
171   113  4.8  7.900  0.0  12.700  2018.0   264      27        False   
196   138  4.5  7.766  0.0  12.266  2018.0   279      38        False   
391   131  4.9  7.633  0.0  12.533  2019.0   291      12        False   
113    55  4.9  8.533  0.0  13.433  2018.0   182      26        False   

     round_qual  
71         True  
171        True  
196        True  
391        True  
113        True

In [7]:
olymp.head()


Rank  D Score  E Score  Pen.   Total  year  Name  nation  round_AAfinal  \
0  73.0      3.5    8.366   0.0  11.866  2023   242      62          False   
1  12.0      5.3    7.933   0.0  13.233  2022   523      27           True   
2  90.0      4.9    7.666   0.0  12.566  2022   523      27          False   
3   0.0      5.3    8.500   0.0  13.800  2022   523      27          False   
4  23.0      5.3    8.366   0.0  13.666  2022   523      27          False   

   round_TeamFinal  round_TeamQual  round_final  round_qual  
0            False           False        False        True  
1            False           False        False       False  
2            False           False        False        True  
3             True           False        False       False  
4            False           False        False        True

In [8]:
olymp.rename(columns={'D Score': 'D', 'E Score': 'E',
                     'Pen.': 'ND', 'nation': 'Nation'}, inplace=True)

In [9]:
olymp=olymp.drop(columns=['round_TeamFinal', 'round_AAfinal', 'round_TeamQual'])

In [10]:
from sklearn.tree import DecisionTreeClassifier, plot_tree

In [11]:
df1 = df.copy()

In [12]:
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()
# df_normalized = pd.DataFrame(scaler.fit_transform(df1), columns=df.columns)


In [13]:
# import matplotlib.pyplot as plt
# from sklearn.tree import DecisionTreeClassifier, plot_tree
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score, confusion_matrix

# # Assuming you already have your DataFrame 'df' and the target variable is 'medal'
# y = df['medal']
# X = df.drop(columns=['medal'])

# # Convert class labels to strings
# class_names = df['medal'].astype(str).unique()

# # Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.28, random_state=110)

# clf = DecisionTreeClassifier()
# clf.fit(X_train, y_train)

# # Make predictions on the test data
# y_pred = clf.predict(X_test)

# # Calculate accuracy
# accuracy = accuracy_score(y_test, y_pred)

# # Generate confusion matrix
# conf_matrix = confusion_matrix(y_test, y_pred)

# # Plot the Decision Tree
# plt.figure(figsize=(12, 8))
# plot_tree(clf, filled=True, feature_names=X.columns, class_names=class_names)
# plt.title("Decision Tree Classifier")
# plt.show()

# # Print accuracy and confusion matrix
# print(f"Accuracy: {accuracy:.4f}")
# print("Confusion Matrix:")
# print(conf_matrix)


In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

y = df['medal']
X = df.drop(columns=['medal'])

# Convert class labels to strings
class_names = df['medal'].astype(str).unique()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.28, random_state=110)

# Initialize and train a RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Make predictions with class probabilities
class_probs = rf_model.predict_proba(X_test)

# Define the number of top classes to select
top_n = 3

# Select the top N classes based on class probabilities
top_n_classes = np.argsort(class_probs, axis=1)[:, -top_n:]

# Set the minimum probability threshold
min_probability_threshold = 0.02

# Apply the threshold to select the top N classes
top_n_classes = top_n_classes[class_probs[np.arange(len(class_probs)), top_n_classes[:, -1]] >= min_probability_threshold]

# Evaluate the model's accuracy using the top N results
y_pred = top_n_classes[:, -1]  # Select the top prediction from the top N
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy (Top {top_n}): {accuracy:.4f}")


Accuracy (Top 3): 0.9928


In [15]:
class_probs = rf_model.predict_proba(olymp)

# Define the number of top classes to select
top_n = 20

# Select the top N classes based on class probabilities
top_n_classes = np.argsort(class_probs, axis=1)[:, -top_n:]

# Set the minimum probability threshold
min_probability_threshold = 0.1

# Apply the threshold to select the top N classes
top_n_classes = top_n_classes[class_probs[np.arange(len(class_probs)), top_n_classes[:, -1]] >= min_probability_threshold]

# Evaluate the model's accuracy using the top N results
y_pred = top_n_classes[:, -1]  # Select the top prediction from the top N

In [16]:
ypreds  = pd.Series(y_pred)
olymp['ypred']=ypreds


In [17]:
olymp['ypred'].value_counts()

ypred
0    2305
1      14
Name: count, dtype: int64

In [18]:
filtered_df = olymp[olymp['ypred'] == 1]

In [19]:
filtered_df['Name'].unique()

array([ 10, 731, 732, 336])

In [20]:
name_encoded_values = [ 10, 731, 732, 336]

# Filter the DataFrame to get the corresponding "Name" values
result = srnames.loc[srnames['Name_encoded'].isin(name_encoded_values), 'Name']


In [22]:
result.unique()

array(['adem asil', 'xingyu lan', 'yang liu', 'jingyuan zou'],
      dtype=object)

In [23]:
srolymp["Name"]=srolymp["Name"].str.lower()


In [24]:
names_to_filter =['adem asil', 'xingyu lan', 'yang liu', 'jingyuan zou']

# Filter the DataFrame to get rows with the specified "Name" values
result = srolymp[srolymp['Name'].isin(names_to_filter)]

In [25]:
result['Country'].value_counts()

Country
TUR    121
CHN     48
Name: count, dtype: int64